### ISSUE TITLE
mpi4py-fft with Apple Silicon M1/M2?

### ISSUE THREAD

**Issue by pancetta** [mpi4py/mpi4py-fft#28]
Looks like `mpi4py-fft` cannot easily be installed on an M1 or M2 arm-based architecture. Using `conda` does not work, because only recipes for `osx-64` and `linux-64` are given. Using `pip` fails (for me) with

```
      [...]
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cimport fftwf_xfftn
              ^
      ------------------------------------------------------------
      
      mpi4py_fft/fftw/fftwf_xfftn.pyx:1:8: 'fftwf_xfftn.pxd' not found
      [...]
```
Any ideas?

**Comment by mikaem** [comment]
Hi,
I guess we simply need to add `osx-arm64` platform on [the conda feedstock](https://github.com/conda-forge/mpi4py-fft-feedstock). You are more than welcome to try a PR to this end over there:-)

**Comment by mikaem** [comment]
@pancetta I just tried to add this in a [PR](https://github.com/conda-forge/mpi4py-fft-feedstock/pull/28) and the error message you refer to here is simply due to using cython version 3.0.0, which was released a month ago. I rolled back to cython < 1.0, but then I got a new arm-related [error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=757383&view=logs&j=c35410bf-a820-56fd-e231-d3cd4bead63c&t=b92b255f-9dfe-5c14-4730-460f7a671001), where I'm stuck.

**Comment by pancetta** [comment]
Hey @mikaem, thanks for trying!

**Comment by mikaem** [comment]
Including osx-arm64 taken care of [here](https://github.com/conda-forge/mpi4py-fft-feedstock/pull/28).
Update to cython 3 going on here: #29
